instruments = ["Piano accoustique",
               "Piano brillant",
               "Piano électrique",
               "Piano bastringue",
               "Piano électrique 1",
               "Piano électrique 2",
               "Piano clavecin",
               "Piano clavinette",
               "Xylophone célecta",
               "Xylophone glockenspiel",
               "Boîte à musique",
               "Vibraphone",
               "Marimba",
               "Xylophone",
               "Tubular Bells",
               "Dulcimer",
               "Orgue Hammond",
               "Orgue percussive",
               "Orgue rock",
               "Orgue église",
               "Orgue Harmonium",
               "Orgue accordéon",
               "Orgue Harmonica",
               "Orgue Bandonéon",
               "Guitare cordes en Nylon",
               "Guitare cordes en acier",
               "Guitare Jazz",
               "Guitare claire",
               "Guitare étouffée",
               "Guitare saturée",
               "Guitare distortion",
               "Guitare harmonique",
               "Basse accoustique",
               "Basse au doigt",
               "Basse au plectre",
               "Basse fretless",
               "Basse slap 1",
               "Basse slap 2",
               "Basse synthé 1",
               "Basse synthé 2",
               "Violon",
               "Alto",
               "Cello",
               "Contrebasse",
               "Section trémolo",
               "Section pizzicato",
               "Section cordes",
               "Timbales",
               "Cordes 1",
               "Cordes cordes 2",
               "Synthé cordes 1",
               "Synthé 2",
               "Chœur Ah",
               "Chœur Oh",
               "Voix",
               "Coups",
               "Trompette",
               "Trombone",
               "Tuba",
               "Trompette bouchée",
               "Corps d'harmonie",
               "Section cuivre",
               "Synthé cuivre 1",
               "Synthé cuivre 2",
               "Sax soprano",
               "Sax alto",
               "Sax ténor",
               "sax baryton",
               "hautbois",
               "Cor anglais",
               "Basson",
               "Clarinette",
               "Flûte piccolo",
               "Flûte",
               "Flûte à bec",
               "Flûte de Pan",
               "Bouteille",
               "Sakuhachi",
               "Sifflet",
               "Ocarina",
               "Ondes carrées",
               "Dent de scie",
               "Calliope",
               "Chiff",
               "Charang",
               "Voix",
               "Quintes",
               "Bass + Lead",
               "Synthé New Age",
               "Synthé chaud",
               "Synthé froid",
               "Synthé poly",
               "Synthé chœur",
               "Synthé archet",
               "Synthé métallique",
               "Synthé halo",
               "Synthé sweep",
               "Synthé pluie",
               "Synthé soundtrack",
               "Synthé cristal",
               "Synthé atmosphère",
               "Synthé brillance",
               "Synthé goblins",
               "Synthé écho",
               "Synthé SF",
               "Sitar",
               "Banjo",
               "Shamisen",
               "Koto",
               "Kalimba",
               "Cornemuse",
               "Viole",
               "Shanai",
               "Cloche",
               "Agogo",
               "Steel drum",
               "Woodblock",
               "Taiko",
               "Tom",
               "Synthé percussions",
               "Cymbale inverse",
               "Bruit de guitare",
               "Respiration",
               "Plage",
               "Cui-cui",
               "Téléphone",
               "Hélicoptère",
               "Applaudissements",
               "Revolver"]
